In [1]:
# Thrid party libs
import dask.dataframe as dd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

# System libs
import datetime as dt
import time
import os
import csv
import sys
sys.path.append(os.path.join(os.getcwd(), ".."))

# Local imports
from utils import normalize_embeddings
import examples

In [2]:
nested_list = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 0, 1, 2],
    [3, 4, 5, 6],
    [7, 8, 9, 0],
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 0, 1, 2],
    [3, 4, 5, 6],
    [7, 8, 9, 0]
]

In [3]:
result = normalize_embeddings(nested_list)

In [4]:
result

[array([0.18257419, 0.36514837, 0.54772256, 0.73029674]),
 array([0.37904902, 0.45485883, 0.53066863, 0.60647843]),
 array([0.97049496, 0.        , 0.10783277, 0.21566555]),
 array([0.32349832, 0.43133109, 0.53916387, 0.64699664]),
 array([0.50257071, 0.57436653, 0.64616234, 0.        ]),
 array([0.18257419, 0.36514837, 0.54772256, 0.73029674]),
 array([0.37904902, 0.45485883, 0.53066863, 0.60647843]),
 array([0.97049496, 0.        , 0.10783277, 0.21566555]),
 array([0.32349832, 0.43133109, 0.53916387, 0.64699664]),
 array([0.50257071, 0.57436653, 0.64616234, 0.        ])]